theme: jekyll-theme-minimal
title: Homepage
# description: 
header_pages:
  - about.md
  - research.md
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
